import { createDarkTheme, darkThemePrimitives } from "baseui";

export const APP_THEME_COLOR_KEYS = [
	"bgPrimary",
	"bgSecondary",
	"bgTertiary",
	"bgQuaternary",
	"bgOffRange",
	"textPrimary",
	"textSecondary",
	"textTertiary",
	"textMuted",
	"textSubtle",
	"textFaint",
	"textOnPrimary",
	"textDisabled",
	"textDisabledAlt",
	"textOnMuted",
	"accent100",
	"accent200",
	"accent300",
	"accent400",
	"accent500",
	"accent600",
	"accent700",
	"accent800",
	"borderPrimary",
	"borderTransparent",
	"successBg",
	"successText",
	"success",
	"successLight",
	"errorBg",
	"errorHover",
	"errorText",
	"error",
	"warning",
	"warningLight",
	"warningBg",
	"warningDarkBg",
	"warningDarkHover",
	"info",
	"overlay",
] as const;

export type AppColorKey = (typeof APP_THEME_COLOR_KEYS)[number];
export type AppColors = Record<AppColorKey, string>;

export const DEFAULT_APP_COLORS: AppColors = {
	bgPrimary: "#0a0a0a",
	bgSecondary: "#141414",
	bgTertiary: "#1e1e1e",
	bgQuaternary: "#2a2a2a",
	bgOffRange: "#0f0f0f",
	textPrimary: "#e0d6f0",
	textSecondary: "#b8a9d4",
	textTertiary: "#8b7aab",
	textMuted: "#888",
	textSubtle: "#9ca3af",
	textFaint: "#a99cbc",
	textOnPrimary: "#ffffff",
	textDisabled: "#75678f",
	textDisabledAlt: "#6d6282",
	textOnMuted: "#666",
	accent100: "#2e1065",
	accent200: "#3b0764",
	accent300: "#4c1d95",
	accent400: "#5b21b6",
	accent500: "#6d28d9",
	accent600: "#7c3aed",
	accent700: "#8b5cf6",
	accent800: "#a78bfa",
	borderPrimary: "#2a2a2a",
	borderTransparent: "rgba(167, 139, 250, 0.15)",
	successBg: "#1a3525",
	successText: "#a7f3d0",
	success: "#22c55e",
	successLight: "#4ade80",
	errorBg: "#3b1025",
	errorHover: "#4d1530",
	errorText: "#fca5a5",
	error: "#ef4444",
	warning: "#f59e0b",
	warningLight: "#fbbf24",
	warningBg: "rgba(245, 158, 11, 0.2)",
	warningDarkBg: "#2a1f14",
	warningDarkHover: "#3a2a1b",
	info: "#2dd4bf",
	overlay: "rgba(0, 0, 0, 0.5)",
};

export const APP_COLORS = DEFAULT_APP_COLORS;

export function createAppColorVars(colors: AppColors): Record<string, string> {
	return {
		"--color-bg-primary": colors.bgPrimary,
		"--color-bg-secondary": colors.bgSecondary,
		"--color-bg-tertiary": colors.bgTertiary,
		"--color-bg-quaternary": colors.bgQuaternary,
		"--color-bg-off-range": colors.bgOffRange,
		"--color-text-primary": colors.textPrimary,
		"--color-text-secondary": colors.textSecondary,
		"--color-text-tertiary": colors.textTertiary,
		"--color-text-muted": colors.textMuted,
		"--color-text-subtle": colors.textSubtle,
		"--color-text-faint": colors.textFaint,
		"--color-text-on-primary": colors.textOnPrimary,
		"--color-text-disabled": colors.textDisabled,
		"--color-text-disabled-alt": colors.textDisabledAlt,
		"--color-text-on-muted": colors.textOnMuted,
		"--color-accent-100": colors.accent100,
		"--color-accent-200": colors.accent200,
		"--color-accent-300": colors.accent300,
		"--color-accent-400": colors.accent400,
		"--color-accent-500": colors.accent500,
		"--color-accent-600": colors.accent600,
		"--color-accent-700": colors.accent700,
		"--color-accent-800": colors.accent800,
		"--color-border-primary": colors.borderPrimary,
		"--color-border-transparent": colors.borderTransparent,
		"--color-success-bg": colors.successBg,
		"--color-success-text": colors.successText,
		"--color-success": colors.success,
		"--color-success-light": colors.successLight,
		"--color-error-bg": colors.errorBg,
		"--color-error-hover": colors.errorHover,
		"--color-error-text": colors.errorText,
		"--color-error": colors.error,
		"--color-warning": colors.warning,
		"--color-warning-light": colors.warningLight,
		"--color-warning-bg": colors.warningBg,
		"--color-warning-dark-bg": colors.warningDarkBg,
		"--color-warning-dark-hover": colors.warningDarkHover,
		"--color-info": colors.info,
		"--color-overlay": colors.overlay,
	};
}

export const applyAppColorVariables = (
	colors: AppColors,
	root: HTMLElement = document.documentElement,
) => {
	for (const [name, value] of Object.entries(createAppColorVars(colors))) {
		root.style.setProperty(name, value);
	}
};

export function createAppTheme(colors: AppColors) {
	const primitives = {
		...darkThemePrimitives,
		primaryFontFamily:
			"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
		primary: colors.accent800,
		primary50: colors.accent100,
		primary100: colors.accent200,
		primary200: colors.accent300,
		primary300: colors.accent400,
		primary400: colors.accent500,
		primary500: colors.accent600,
		primary600: colors.accent700,
		primary700: colors.accent800,
	};

	const baseTheme = createDarkTheme(primitives);

	return {
		...baseTheme,
		colors: {
			...baseTheme.colors,
			backgroundPrimary: colors.bgPrimary,
			backgroundSecondary: colors.bgSecondary,
			backgroundTertiary: colors.bgTertiary,
			contentPrimary: colors.textPrimary,
			contentSecondary: colors.textSecondary,
			contentTertiary: colors.textTertiary,
			inputFill: colors.bgTertiary,
			inputFillActive: colors.bgQuaternary,
			inputBorder: colors.accent300,
			inputFillError: colors.errorBg,
			inputFillPositive: colors.successBg,
			buttonPrimaryFill: colors.accent600,
			buttonPrimaryHover: colors.accent500,
			buttonPrimaryActive: colors.accent400,
			buttonPrimaryText: colors.textOnPrimary,
			buttonSecondaryFill: colors.bgTertiary,
			buttonSecondaryHover: colors.bgQuaternary,
			buttonSecondaryActive: colors.accent300,
			buttonSecondaryText: colors.textPrimary,
			menuFill: colors.bgSecondary,
			menuFillHover: colors.bgTertiary,
			tableHeadBackgroundColor: colors.bgSecondary,
			tableBackground: colors.bgPrimary,
			tableStripedBackground: colors.bgSecondary,
			tickFill: colors.bgTertiary,
			tickFillActive: colors.accent600,
			tickFillSelected: colors.accent600,
			tickFillSelectedHover: colors.accent500,
			tickMarkFill: colors.textOnPrimary,
			notificationInfoBackground: colors.bgTertiary,
			notificationInfoText: colors.textPrimary,
			toastInfoBackground: colors.bgTertiary,
			toastInfoText: colors.textPrimary,
			toastPositiveBackground: colors.successBg,
			toastPositiveText: colors.successText,
			toastNegativeBackground: colors.errorBg,
			toastNegativeText: colors.errorText,
			borderOpaque: colors.borderPrimary,
			borderTransparent: colors.borderTransparent,
			modalCloseColor: colors.textSecondary,
		},
	};
}
