import { createDarkTheme, darkThemePrimitives } from "baseui";

export const APP_COLORS = {
	bgPrimary: "#0a0a0a",
	bgSecondary: "#141414",
	bgTertiary: "#1e1e1e",
	bgQuaternary: "#2a2a2a",
	bgOffRange: "#0f0f0f",
	textPrimary: "#e0d6f0",
	textSecondary: "#b8a9d4",
	textTertiary: "#8b7aab",
	textMuted: "#888",
	textSubtle: "#9ca3af",
	textFaint: "#a99cbc",
	textOnPrimary: "#ffffff",
	textDisabled: "#75678f",
	textDisabledAlt: "#6d6282",
	textOnMuted: "#666",
	accent100: "#2e1065",
	accent200: "#3b0764",
	accent300: "#4c1d95",
	accent400: "#5b21b6",
	accent500: "#6d28d9",
	accent600: "#7c3aed",
	accent700: "#8b5cf6",
	accent800: "#a78bfa",
	borderPrimary: "#2a2a2a",
	borderTransparent: "rgba(167, 139, 250, 0.15)",
	successBg: "#1a3525",
	successText: "#a7f3d0",
	success: "#22c55e",
	successLight: "#4ade80",
	errorBg: "#3b1025",
	errorHover: "#4d1530",
	errorText: "#fca5a5",
	error: "#ef4444",
	warning: "#f59e0b",
	warningLight: "#fbbf24",
	warningBg: "rgba(245, 158, 11, 0.2)",
	warningDarkBg: "#2a1f14",
	warningDarkHover: "#3a2a1b",
	info: "#2dd4bf",
	overlay: "rgba(0, 0, 0, 0.5)",
} as const;

export const APP_COLOR_VARS = {
	"--color-bg-primary": APP_COLORS.bgPrimary,
	"--color-bg-secondary": APP_COLORS.bgSecondary,
	"--color-bg-tertiary": APP_COLORS.bgTertiary,
	"--color-bg-quaternary": APP_COLORS.bgQuaternary,
	"--color-bg-off-range": APP_COLORS.bgOffRange,
	"--color-text-primary": APP_COLORS.textPrimary,
	"--color-text-secondary": APP_COLORS.textSecondary,
	"--color-text-tertiary": APP_COLORS.textTertiary,
	"--color-text-muted": APP_COLORS.textMuted,
	"--color-text-subtle": APP_COLORS.textSubtle,
	"--color-text-faint": APP_COLORS.textFaint,
	"--color-text-on-primary": APP_COLORS.textOnPrimary,
	"--color-text-disabled": APP_COLORS.textDisabled,
	"--color-text-disabled-alt": APP_COLORS.textDisabledAlt,
	"--color-text-on-muted": APP_COLORS.textOnMuted,
	"--color-accent-100": APP_COLORS.accent100,
	"--color-accent-200": APP_COLORS.accent200,
	"--color-accent-300": APP_COLORS.accent300,
	"--color-accent-400": APP_COLORS.accent400,
	"--color-accent-500": APP_COLORS.accent500,
	"--color-accent-600": APP_COLORS.accent600,
	"--color-accent-700": APP_COLORS.accent700,
	"--color-accent-800": APP_COLORS.accent800,
	"--color-border-primary": APP_COLORS.borderPrimary,
	"--color-border-transparent": APP_COLORS.borderTransparent,
	"--color-success-bg": APP_COLORS.successBg,
	"--color-success-text": APP_COLORS.successText,
	"--color-success": APP_COLORS.success,
	"--color-success-light": APP_COLORS.successLight,
	"--color-error-bg": APP_COLORS.errorBg,
	"--color-error-hover": APP_COLORS.errorHover,
	"--color-error-text": APP_COLORS.errorText,
	"--color-error": APP_COLORS.error,
	"--color-warning": APP_COLORS.warning,
	"--color-warning-light": APP_COLORS.warningLight,
	"--color-warning-bg": APP_COLORS.warningBg,
	"--color-warning-dark-bg": APP_COLORS.warningDarkBg,
	"--color-warning-dark-hover": APP_COLORS.warningDarkHover,
	"--color-info": APP_COLORS.info,
	"--color-overlay": APP_COLORS.overlay,
} as const;

export const applyAppColorVariables = (
	root: HTMLElement = document.documentElement,
) => {
	for (const [name, value] of Object.entries(APP_COLOR_VARS)) {
		root.style.setProperty(name, value);
	}
};

const primitives = {
	...darkThemePrimitives,
	primaryFontFamily:
		"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
	primary: APP_COLORS.accent800,
	primary50: APP_COLORS.accent100,
	primary100: APP_COLORS.accent200,
	primary200: APP_COLORS.accent300,
	primary300: APP_COLORS.accent400,
	primary400: APP_COLORS.accent500,
	primary500: APP_COLORS.accent600,
	primary600: APP_COLORS.accent700,
	primary700: APP_COLORS.accent800,
};

const baseTheme = createDarkTheme(primitives);

export const theme = {
	...baseTheme,
	colors: {
		...baseTheme.colors,
		backgroundPrimary: APP_COLORS.bgPrimary,
		backgroundSecondary: APP_COLORS.bgSecondary,
		backgroundTertiary: APP_COLORS.bgTertiary,
		contentPrimary: APP_COLORS.textPrimary,
		contentSecondary: APP_COLORS.textSecondary,
		contentTertiary: APP_COLORS.textTertiary,
		inputFill: APP_COLORS.bgTertiary,
		inputFillActive: APP_COLORS.bgQuaternary,
		inputBorder: APP_COLORS.accent300,
		inputFillError: APP_COLORS.errorBg,
		inputFillPositive: APP_COLORS.successBg,
		buttonPrimaryFill: APP_COLORS.accent600,
		buttonPrimaryHover: APP_COLORS.accent500,
		buttonPrimaryActive: APP_COLORS.accent400,
		buttonPrimaryText: APP_COLORS.textOnPrimary,
		buttonSecondaryFill: APP_COLORS.bgTertiary,
		buttonSecondaryHover: APP_COLORS.bgQuaternary,
		buttonSecondaryActive: APP_COLORS.accent300,
		buttonSecondaryText: APP_COLORS.textPrimary,
		menuFill: APP_COLORS.bgSecondary,
		menuFillHover: APP_COLORS.bgTertiary,
		tableHeadBackgroundColor: APP_COLORS.bgSecondary,
		tableBackground: APP_COLORS.bgPrimary,
		tableStripedBackground: APP_COLORS.bgSecondary,
		tickFill: APP_COLORS.bgTertiary,
		tickFillActive: APP_COLORS.accent600,
		tickFillSelected: APP_COLORS.accent600,
		tickFillSelectedHover: APP_COLORS.accent500,
		tickMarkFill: APP_COLORS.textOnPrimary,
		notificationInfoBackground: APP_COLORS.bgTertiary,
		notificationInfoText: APP_COLORS.textPrimary,
		toastInfoBackground: APP_COLORS.bgTertiary,
		toastInfoText: APP_COLORS.textPrimary,
		toastPositiveBackground: APP_COLORS.successBg,
		toastPositiveText: APP_COLORS.successText,
		toastNegativeBackground: APP_COLORS.errorBg,
		toastNegativeText: APP_COLORS.errorText,
		borderOpaque: APP_COLORS.borderPrimary,
		borderTransparent: APP_COLORS.borderTransparent,
		modalCloseColor: APP_COLORS.textSecondary,
	},
};
